version: '3.5'

services:
  iam-app:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - PORT=${PORT} 
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal